# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16c5810ecf1074ee5d4ddffaeaf540057b05fda7a8b66e8fc3fc2fb8a866dfd6a07a411daa7fd94c6d4b169d6730349e10627d267a8a675ab13de5433b5058b6

test:
  secret_key_base: 6430128d1f763485c05a178ccdf65bef90247b3158bfccfad251875ece8a18aaea893d1a2ab1c8392402bcdafee464ad8e07e4c5848f2f4945648bd824c85df1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  tiny_mce_api_key: <%= ENV["TINY_MCE_API_KEY"] %>
